### ISSUE TITLE
Indiana Jones and the Fate of Atlantis won't load.

### ISSUE THREAD

**Issue by gamaral** [Liquidream/scumm-8#10]
Just kidding. ;-)

**Comment by Liquidream** [comment]
Hahaha! Love it! 🤣 

You just wait - **SOMEONE** will actually mean it one day and it will take all my willpower NOT to post the following...  😜 

![scumm-8 meme](https://cloud.githubusercontent.com/assets/2211678/25192707/3793e498-252c-11e7-9335-cc85fcc2ceff.jpg)

**Comment by gamaral** [comment]
Oh, I know they will. ;-)
I hope you kept your email private also... oh boy, the emails.

**Comment by Liquidream** [comment]
Oh fuuuuuu... 🙄

#OnlyJoking #ProbablyOk #Probably
