### ISSUE TITLE
Build step

### ISSUE THREAD

**Issue by benwiley4000** [Liquidream/scumm-8#14]
Would it be possible to include an automated build step as part of the repo so any changes to the engine can be built and reflected in the minified version included in the template?

**Comment by Liquidream** [comment]
Hi Ben,

Well, I dunno how to make automated build steps within the repo (is that even possible with GitHub?), but if you mean to just include the ability to re-minify the engine code - then that's a good point, and something I've been meaning to do - and would like to find a way to do in one, automated step.

For now tho, I'll detail below how I minify the engine code, using a *slightly* tweaked version of [picotool](https://github.com/dansanderson/picotool)'s **luamin** function (made by [Dan Sanderson](https://github.com/dansanderson)).
_(The tweaks are to it's minifying parser to ensure it preserves SCUMM-8 API reserved words)_

### (Re)Minifying the SCUMM-8 Engine Code
1. Download and extract the "tweaked" build of picotool, linked below:
[picotool-scumm8.zip](https://github.com/Liquidream/scumm-8/files/1863072/picotool-scumm8.zip)

2. Make your changes to the engine (SCUMM-8.p8), then re-minify the code using this command:
`<path-to-picotool-scumm8>/p8tool luamin <path-to-SCUMM-8>/scumm-8.p8`
_(You might need to add "`python `" at the start, if using Windows)_

3. Now edit the generated, now-minified "scumm-8_fmt.p8" file in a text/code editor.
Search for "`function shake(`" (the start of the actual API - not the sample game), then select the code all the way down to before the "`__gfx__`" section.
Copy and paste this minified engine code to your game cart.

4. Finally, restore some original character codes (that luamin converts to UPPERCASE), by looking at the end of the engine code for:
`"ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\"`
and replacing it with:
`"\65\66\67\68\69\70\71\72\73\74\75\76\77\78\79\80\81\82\83\84\85\86\87\88\89\90\91\92"`

**NOTE:**
_If you ever get an "Invalid .p8: missing or corrupt header" error from using picotool, just open the .p8 file you're trying to process into PICO-8 and re-save it._

Hope this helps! 😄

**Comment by benwiley4000** [comment]
Thanks for the detailed steps! Indeed, I'm not looking for any kind of fancy GitHub integration, just an automated step to build locally. I opened a [PR](https://github.com/Liquidream/scumm-8/pull/15) to automate this. :slightly_smiling_face:

**Comment by Liquidream** [comment]
Thanks again for your contributions on this - should make any further engine modifications MUCH easier to test/port to other carts! 🙏
