### ISSUE TITLE
Click to skip dialogue

### ISSUE THREAD

**Issue by tobiasvl** [Liquidream/scumm-8#17]
[CODE-8](https://gamejolt.com/games/code-8/340837) adds a feature where dialogue can be skipped by clicking the mouse button.

This should be natively supported in SCUMM-8.

**Comment by Liquidream** [comment]
You are absolutely right, Sir.
My development branch has all the all of SCUMM-8's new features included.
Alas, I am long overdue pulling these changes into "master" (I wanted to do more testing - got sidetracked!) - my bad.
Expect to see a big update soon! 😉

**Comment by Liquidream** [comment]
[v1.1 Update](https://github.com/Liquidream/scumm-8/releases/tag/v1.1) is now live! 🚀
