### ISSUE TITLE
Bug in /template/game.p8

### ISSUE THREAD

**Issue by doritos4mlady** [Liquidream/scumm-8#25]
I noticed a bug in game.p8

To replicate:

1: Use purple tentacle
2: Move to the right
3: Use humanoid
4: Try to walk past the tentacle

The tentacle will repeat "STOP! COME BACK HERE!" ad infinitum

**Comment by doritos4mlady** [comment]
I tried to replicate again and couldn't, weird. So my replication instructions dont work

**Comment by Liquidream** [comment]
Yeah, ability to switch chars was a quick demo of the [concept](https://github.com/Liquidream/scumm-8/wiki/SCUMM-8-Tutorial%3A-Switchable-Characters), so wouldn't be surprised if there's a couple of edge-cases.
Thanks for report, though.
